# Generated by Django 3.1.4 on 2020-12-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carsName', models.CharField(max_length=255, verbose_name='Cars name')),
                ('merk', models.CharField(max_length=255, verbose_name='Merk')),
                ('plat', models.CharField(max_length=10, verbose_name='Plat')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
