# Generated by Django 3.1.4 on 2020-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='merk',
        ),
        migrations.AddField(
            model_name='cars',
            name='Carype',
            field=models.CharField(default='', max_length=255, verbose_name='Types'),
        ),
        migrations.AddField(
            model_name='cars',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='Brand name'),
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(default='', max_length=255, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='plat',
            field=models.CharField(default='', max_length=10, verbose_name='Plat'),
        ),
    ]
