# Generated by Django 3.1.4 on 2020-12-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20201228_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentDate', models.DateTimeField(auto_now_add=True, verbose_name='Rent Date')),
                ('rentDateBack', models.DateTimeField(auto_now_add=True, verbose_name='Rent Date Back')),
                ('plat', models.CharField(default='', max_length=10, verbose_name='Plat')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('idCars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.cars')),
            ],
        ),
    ]
