# Generated by Django 3.1.4 on 2020-12-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='idContact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crudapp.contact'),
        ),
    ]
