# Generated by Django 3.1.4 on 2020-12-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_rent_idcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='idContact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crudapp.contact'),
        ),
    ]
