# Generated by Django 3.1.4 on 2020-12-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20201229_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='idContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.contact'),
        ),
    ]
